import { IPromotion } from '@spt/core';

export const mockedPromotions: IPromotion[] = [
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
];

const mockOffer = {
  id: Math.random().toString() + Math.random().toString(),
  image: 'https://api.spt.sa/uploads/site_offers/1729442146Group 1 (1).png',
  title: 'قم ببيع سارتك التشاليح',
  title_ar: 'قم ببيع سارتك التشاليح',
  title_en: 'Maintain your car',
  description:
    'عرض صيانة السيارة: 500 ريال بدلاً من 350 ريال\r\nهل تبحث عن فرصة ممتازة لصيانة سيارتك والحفاظ عليها في أفضل حالاتها؟ نقدم لك عرضًا خاصًا لا يفوت! احصل على خدمة صيانة شاملة لسيارتك بسعر 500 ريال بدلاً من 350 ريال فقط.',
  description_ar:
    'عرض صيانة السيارة: 500 ريال بدلاً من 350 ريال\r\nهل تبحث عن فرصة ممتازة لصيانة سيارتك والحفاظ عليها في أفضل حالاتها؟ نقدم لك عرضًا خاصًا لا يفوت! احصل على خدمة صيانة شاملة لسيارتك بسعر 500 ريال بدلاً من 350 ريال فقط.',
  description_en:
    'Car maintenance offer: 500 riyals instead of 350 riyals\r\nAre you looking for an excellent opportunity to maintain your car and keep it in its best condition? We offer you a special offer not to be missed! Get a comprehensive maintenance service for your car for 500 riyals instead of only 350 riyals.',
  price_before_discount: '500.00',
  price_after_discount: '350.00',
  deleted_at: null,
};

export const mockResponse = {
  success: true,
  message: 'تمت العملية بنجاح',
  data: {
    data: Array.from({ length: 10 }).map((_, index) => mockOffer),
    links: {
      first: 'https://api.spt.sa/api/v1/site_offers?page=1',
      last: 'https://api.spt.sa/api/v1/site_offers?page=3',
      prev: null,
      next: 'https://api.spt.sa/api/v1/site_offers?page=2',
    },
    meta: {
      current_page: 1,
      from: 1,
      last_page: 30,
      per_page: 1,
      to: 1,
      total: 3,
    },
  },
};
