import { Offer } from '@spt/core';

export const mockedOffers: Offer[] = [
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
  {
    id: '1',
    image: 'https://picsum.photos/400/300',
    title: 'صفقة مذهلة على أجهزة اللاب توب',
    title_ar: 'صفقة مذهلة على أجهزة اللاب توب',
    title_en: 'Amazing Deal on Laptops',
    description: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_ar: 'احصل على أحدث أجهزة اللاب توب بخصومات ضخمة.',
    description_en: 'Get the latest laptops with huge discounts.',
    price_before_discount: '1400',
    price_after_discount: '899',
    deleted_at: null,
  },
];
