// This file is auto-generated by @hey-api/openapi-ts

export type GetSharedAuthMeData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetSharedAuthMeResponse = unknown;

export type PostSharedAuthRegisterData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        name?: string;
        phone?: number;
        avatar?: (Blob | File);
        city_id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthRegisterResponse = {
    [key: string]: unknown;
};

export type PostSharedAuthSendOtpData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthSendOtpResponse = {
    [key: string]: unknown;
};

export type PostSharedAuthVerifyOtpData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthVerifyOtpResponse = {
    [key: string]: unknown;
};

export type PostSharedAuthLogoutData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthLogoutResponse = {
    [key: string]: unknown;
};

export type PostSharedAuthEditProfileData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        name?: string;
        city_id?: number;
        avatar?: (Blob | File);
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthEditProfileResponse = unknown;

export type PostSharedAuthChangePhoneData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthChangePhoneResponse = unknown;

export type PostSharedAuthVerifyChangePhoneData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostSharedAuthVerifyChangePhoneResponse = unknown;

export type PutSharedAuthUpdateSettingsData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PutSharedAuthUpdateSettingsResponse = unknown;

export type GetBrandsData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    paginate?: number;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetBrandsResponse = unknown;

export type GetSiteOffersData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    page?: number;
    paginate?: number;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetSiteOffersResponse = unknown;

export type GetCitiesData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    paginate?: number;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetCitiesResponse = unknown;

export type GetBrandsAlfaRomeoModelsData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetBrandsAlfaRomeoModelsResponse = unknown;

export type PostClientOrderSparePartData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        /**
         * valid year
         */
        year?: number;
        /**
         * required | exists in brands
         */
        brand?: string;
        /**
         * required | exists in brand_models
         */
        model?: string;
        /**
         * required if no lat , lng
         */
        address?: string;
        /**
         * required if no address
         */
        latitude?: number;
        /**
         * required if no address
         */
        longitude?: number;
        /**
         * 1 or 0
         */
        is_delivery?: number;
        /**
         * valid date
         */
        delivery_date?: string;
        /**
         * required
         */
        'parts[0][name]'?: string;
        /**
         * required
         */
        'parts[0][quantity]'?: number;
        /**
         * new or used
         */
        'parts[0][condition_new]'?: number;
        'parts[0][condition_used]'?: number;
        'parts[0][condition_both]'?: number;
        /**
         * optional
         */
        'parts[0][notes]'?: string;
        /**
         * optional
         */
        'parts[1][name]'?: string;
        'parts[1][quantity]'?: number;
        'parts[1][condition_new]'?: number;
        'parts[1][condition_used]'?: number;
        'parts[1][condition_both]'?: number;
        'parts[1][notes]'?: string;
        agent_code?: number;
        vin_serial?: string;
        /**
         * optional
         */
        provider_id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostClientOrderSparePartResponse = unknown;

export type GetVinJn8At3Mm3Pw009894Data = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetVinJn8At3Mm3Pw009894Response = unknown;

export type PostChatData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        order_id?: string;
        receiver_id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostChatResponse = unknown;

export type PostChatMessageData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        chat_id?: string;
        content?: string;
        type?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostChatMessageResponse = unknown;

export type GetTicketsData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    page?: number;
    paginate?: number;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetTicketsResponse = unknown;

export type GetTicketB33C269eB489415E842F65472771A0F3Data = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetTicketB33C269eB489415E842F65472771A0F3Response = unknown;

export type PostTicketData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        title?: string;
        content?: string;
        /**
         * optional
         */
        image?: (Blob | File);
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostTicketResponse = unknown;

export type PostTicketMessageData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        ticket_id?: string;
        content?: string;
        /**
         * text or image
         */
        type?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostTicketMessageResponse = unknown;

export type PostCallMakeData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        order_id?: string;
        receiver_id?: string;
        call_type?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostCallMakeResponse = unknown;

export type PostCallAcceptData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostCallAcceptResponse = unknown;

export type PostCallRefuseData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostCallRefuseResponse = unknown;

export type PostCallEndData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostCallEndResponse = unknown;

export type GetNotificationIndexData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    paginate?: number;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetNotificationIndexResponse = unknown;

export type GetNotificationUnreadCountData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetNotificationUnreadCountResponse = unknown;

export type PostNotificationMarkAsReadData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        'notification_ids[0]'?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostNotificationMarkAsReadResponse = unknown;

export type GetAdminOrdersData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    paginate?: number;
    search?: string;
    /**
     * 'receiving_offer','accepted','completed'
     */
    status?: string;
    /**
     * 'spare_parts','towing','junkyard_sale'
     */
    type?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetAdminOrdersResponse = unknown;

export type GetAdminOrders1D9De514C4E149878Eb90909556C7186Data = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetAdminOrders1D9De514C4E149878Eb90909556C7186Response = unknown;

export type GetAdminOrders1D9De514C4E149878Eb90909556C7186OffersData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetAdminOrders1D9De514C4E149878Eb90909556C7186OffersResponse = unknown;

export type GetAdminOrders89572A05E77B48Dc8E1B645Fe0C82B6aChatData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetAdminOrders89572A05E77B48Dc8E1B645Fe0C82B6aChatResponse = unknown;

export type GetSettingCallsResponse = unknown;

export type GetSettingData = {
    /**
     * contact,social_media,notification
     */
    section?: string;
};

export type GetSettingResponse = unknown;

export type PostAdminSettingData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    requestBody?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostAdminSettingResponse = unknown;

export type GetAdminCitiesData = {
    page?: number;
    paginate?: number;
    search?: string;
};

export type GetAdminCitiesResponse = unknown;

export type PostAdminCitiesData = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCitiesResponse = unknown;

export type PutAdminCities81A53C0640694120B9Ae6A4314Cd4AdaData = {
    contentType?: string;
    formData?: {
        name_en?: string;
        name_ar?: string;
    };
};

export type PutAdminCities81A53C0640694120B9Ae6A4314Cd4AdaResponse = unknown;

export type DeleteAdminCitiesB4A072761Baf43B08068C03Fdabf2626Response = unknown;

export type PostAdminCities0E3685698D074EfbA367182Dd5E2Db42StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCities0E3685698D074EfbA367182Dd5E2Db42StopResponse = unknown;

export type PostAdminCities0E3685698D074EfbA367182Dd5E2Db42RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCities0E3685698D074EfbA367182Dd5E2Db42RestoreResponse = unknown;

export type GetAdminProviderProfilesData = {
    page?: number;
    paginate?: number;
};

export type GetAdminProviderProfilesResponse = unknown;

export type PostAdminProviderProfilesVerify09D88C1dFd8A424D9E7cA5D2391Cdbd3Data = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminProviderProfilesVerify09D88C1dFd8A424D9E7cA5D2391Cdbd3Response = unknown;

export type PostAdminProviderProfilesDecline02B915A75A5647118B4aEb110408A090Data = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminProviderProfilesDecline02B915A75A5647118B4aEb110408A090Response = unknown;

export type PostAdminProviderProfilesStop02B915A75A5647118B4aEb110408A090Data = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminProviderProfilesStop02B915A75A5647118B4aEb110408A090Response = unknown;

export type PostAdminProviderProfilesRestore02B915A75A5647118B4aEb110408A090Data = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminProviderProfilesRestore02B915A75A5647118B4aEb110408A090Response = unknown;

export type GetAdminUsersData = {
    accept?: string;
    page?: number;
    paginate?: number;
    /**
     * ADMIN BUSINESS CLIENT
     */
    role?: string;
};

export type GetAdminUsersResponse = unknown;

export type PostAdminUsersData = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminUsersResponse = unknown;

export type GetAdminUsers72D5778fB67B4E97B4E2F98F695162A7Data = {
    accept?: string;
};

export type GetAdminUsers72D5778fB67B4E97B4E2F98F695162A7Response = unknown;

export type PutAdminUsersB2Ef1C4F918A4F349D2F97Ce28C2772FData = {
    contentType?: string;
    requestBody?: string;
};

export type PutAdminUsersB2Ef1C4F918A4F349D2F97Ce28C2772FResponse = unknown;

export type DeleteAdminUsersB4A072761Baf43B08068C03Fdabf2626Response = unknown;

export type PostAdminUsers0E3685698D074EfbA367182Dd5E2Db42StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminUsers0E3685698D074EfbA367182Dd5E2Db42StopResponse = unknown;

export type PostAdminUsers0E3685698D074EfbA367182Dd5E2Db42RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminUsers0E3685698D074EfbA367182Dd5E2Db42RestoreResponse = unknown;

export type GetAdminMessageTemplatesData = {
    accept?: string;
    page?: number;
    paginate?: number;
};

export type GetAdminMessageTemplatesResponse = unknown;

export type GetAdminMessageTemplates2Data = {
    accept?: string;
};

export type GetAdminMessageTemplates2Response = unknown;

export type PostAdminMessageTemplates5Data = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminMessageTemplates5Response = unknown;

export type GetAdminServicesData = {
    page?: number;
    paginate?: number;
};

export type GetAdminServicesResponse = unknown;

export type PostAdminServicesData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminServicesResponse = unknown;

export type PostAdminServicesB11D171dEec14474A3D26Ef6881023AeData = {
    accept?: string;
    contentType?: string;
    formData?: {
        name_en?: string;
        name_ar?: string;
        description_ar?: string;
        description_en?: string;
        image?: (Blob | File);
        _method?: string;
    };
};

export type PostAdminServicesB11D171dEec14474A3D26Ef6881023AeResponse = unknown;

export type DeleteAdminServicesB4A072761Baf43B08068C03Fdabf2626Response = unknown;

export type PostAdminServicesD48C07F9B8B846D98B3C3Ba8Fcdbe611StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminServicesD48C07F9B8B846D98B3C3Ba8Fcdbe611StopResponse = unknown;

export type PostAdminServicesD48C07F9B8B846D98B3C3Ba8Fcdbe611RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminServicesD48C07F9B8B846D98B3C3Ba8Fcdbe611RestoreResponse = unknown;

export type GetAdminCommissionsData = {
    page?: number;
    paginate?: number;
};

export type GetAdminCommissionsResponse = unknown;

export type PostAdminCommissionsData = {
    accept?: string;
    page?: number;
    paginate?: number;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCommissionsResponse = unknown;

export type PutAdminCommissions51A7447F3Bfd4E89A7F31969C8Fb9330Data = {
    accept?: string;
    contentType?: string;
    requestBody?: string;
};

export type PutAdminCommissions51A7447F3Bfd4E89A7F31969C8Fb9330Response = unknown;

export type DeleteAdminCommissions51A7447F3Bfd4E89A7F31969C8Fb9330Response = unknown;

export type PostAdminCommissionsD48C07F9B8B846D98B3C3Ba8Fcdbe611StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCommissionsD48C07F9B8B846D98B3C3Ba8Fcdbe611StopResponse = unknown;

export type PostAdminCommissionsD48C07F9B8B846D98B3C3Ba8Fcdbe611RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCommissionsD48C07F9B8B846D98B3C3Ba8Fcdbe611RestoreResponse = unknown;

export type GetAdminPlatformReviewsData = {
    page?: number;
    paginate?: number;
};

export type GetAdminPlatformReviewsResponse = unknown;

export type PostAdminPlatformReviewsData = {
    accept?: string;
    formData?: {
        phone_image?: (Blob | File);
        web_image?: (Blob | File);
    };
};

export type PostAdminPlatformReviewsResponse = unknown;

export type PostAdminPlatformReviews5Data = {
    accept?: string;
    formData?: {
        phone_image?: (Blob | File);
        web_image?: (Blob | File);
    };
};

export type PostAdminPlatformReviews5Response = unknown;

export type DeleteAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330Response = unknown;

export type PostAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330StopResponse = unknown;

export type PostAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330RestoreResponse = unknown;

export type GetAdminPagesRightsResponse = unknown;

export type GetAdminPagesRightsPaginatedData = {
    page?: number;
    paginate?: number;
};

export type GetAdminPagesRightsPaginatedResponse = unknown;

export type PostAdminPagesData = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPagesResponse = unknown;

export type PostAdminPages5Data = {
    accept?: string;
    contentType?: string;
    formData?: {
        content_ar?: string;
        content_en?: string;
        /**
         * optional
         */
        video?: (Blob | File);
        /**
         * optional
         */
        image?: (Blob | File);
    };
};

export type PostAdminPages5Response = unknown;

export type DeleteAdminPages51A7447F3Bfd4E89A7F31969C8Fb9330Response = unknown;

export type GetAdminProviderSubscriptionPlansData = {
    page?: number;
    paginate?: number;
};

export type GetAdminProviderSubscriptionPlansResponse = unknown;

export type PostAdminProviderSubscriptionPlansData = {
    accept?: string;
    contentType?: string;
    formData?: {
        name_en?: string;
        name_ar?: string;
        description_en?: string;
        description_ar?: string;
        summary_en?: string;
        summary_ar?: string;
        image?: (Blob | File);
        price?: number;
        /**
         * months
         */
        duration?: number;
        /**
         * months
         */
        free_duration?: number;
        currency_en?: string;
        currency_ar?: string;
        start_date?: string;
        end_date?: string;
    };
};

export type PostAdminProviderSubscriptionPlansResponse = unknown;

export type PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704Data = {
    accept?: string;
    contentType?: string;
    formData?: {
        name_en?: string;
        name_ar?: string;
        description_en?: string;
        description_ar?: string;
        summary_en?: string;
        summary_ar?: string;
        price?: number;
        days_count?: number;
        currency_en?: string;
        currency_ar?: string;
        start_date?: string;
        end_date?: string;
        image?: (Blob | File);
        duration?: number;
        free_duration?: number;
    };
};

export type PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704Response = unknown;

export type DeleteAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704Response = unknown;

export type PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704StopResponse = unknown;

export type PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704RestoreResponse = unknown;

export type GetAdminCityServicesData = {
    page?: number;
    paginate?: number;
    search?: string;
};

export type GetAdminCityServicesResponse = unknown;

export type PutAdminCityServices13Data = {
    accept?: string;
    contentType?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PutAdminCityServices13Response = unknown;

export type PostAdminCityServicesAttachData = {
    accept?: string;
    contentType?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCityServicesAttachResponse = unknown;

export type PostAdminCityServicesDetachData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCityServicesDetachResponse = unknown;

export type PostAdminCityServices0E3685698D074EfbA367182Dd5E2Db42StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCityServices0E3685698D074EfbA367182Dd5E2Db42StopResponse = unknown;

export type PostAdminCityServices0E3685698D074EfbA367182Dd5E2Db42RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCityServices0E3685698D074EfbA367182Dd5E2Db42RestoreResponse = unknown;

export type PostAdminAuthLoginData = {
    formData?: {
        phone?: number;
        password?: string;
    };
};

export type PostAdminAuthLoginResponse = unknown;

export type PostAdminAuthLogoutData = {
    formData?: {
        email?: string;
        password?: string;
    };
};

export type PostAdminAuthLogoutResponse = unknown;

export type PostAdminCustomNotificationData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminCustomNotificationResponse = unknown;

export type GetAdminPermissionGroupsData = {
    page?: number;
    paginate?: number;
};

export type GetAdminPermissionGroupsResponse = unknown;

export type PostAdminPermissionGroupsData = {
    accept?: string;
    contentType?: string;
    formData?: {
        name_en?: string;
        name_ar?: string;
        'permissions[]'?: string;
    };
};

export type PostAdminPermissionGroupsResponse = unknown;

export type GetAdminPermissionGroups8E0Ea4E1B13645AdAa91F4D0B47DcfafResponse = unknown;

export type PostAdminPermissionGroupsD814419D755547108E26Efeb66Fc8Fc2Data = {
    accept?: string;
    contentType?: string;
    formData?: {
        name_en?: string;
        name_ar?: string;
        'permissions[]'?: string;
    };
};

export type PostAdminPermissionGroupsD814419D755547108E26Efeb66Fc8Fc2Response = unknown;

export type PostAdminPermissionGroups0E3685698D074EfbA367182Dd5E2Db42StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPermissionGroups0E3685698D074EfbA367182Dd5E2Db42StopResponse = unknown;

export type PostAdminPermissionGroups0E3685698D074EfbA367182Dd5E2Db42RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPermissionGroups0E3685698D074EfbA367182Dd5E2Db42RestoreResponse = unknown;

export type DeleteAdminPermissionGroups51A7447F3Bfd4E89A7F31969C8Fb9330Response = unknown;

export type GetAdminPermissionsResponse = unknown;

export type GetAdminMessagesData = {
    accept?: string;
};

export type GetAdminMessagesResponse = unknown;

export type GetAdminMessages8899Eddd256740B6Bcaa85Ed7D53D226Data = {
    accept?: string;
};

export type GetAdminMessages8899Eddd256740B6Bcaa85Ed7D53D226Response = unknown;

export type PostAdminMessagesReply8899Eddd256740B6Bcaa85Ed7D53D226Data = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminMessagesReply8899Eddd256740B6Bcaa85Ed7D53D226Response = unknown;

export type PostAdminMessagesDelete6Aa8Ddfc861C4C42B7C406Dbb20627AdData = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminMessagesDelete6Aa8Ddfc861C4C42B7C406Dbb20627AdResponse = unknown;

export type GetAdminSlidersData = {
    page?: number;
    paginate?: number;
};

export type GetAdminSlidersResponse = unknown;

export type PostAdminSlidersData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
    };
};

export type PostAdminSlidersResponse = unknown;

export type PostAdminSliders726A81EcD9B543Ad946bB77470B071F4Data = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminSliders726A81EcD9B543Ad946bB77470B071F4Response = unknown;

export type DeleteAdminSliders6193D4CdCe8E4B79Ba467E3C086206F3Response = unknown;

export type PostAdminSliders726A81EcD9B543Ad946bB77470B071F4StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminSliders726A81EcD9B543Ad946bB77470B071F4StopResponse = unknown;

export type PostAdminSliders726A81EcD9B543Ad946bB77470B071F4RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminSliders726A81EcD9B543Ad946bB77470B071F4RestoreResponse = unknown;

export type GetAdminHowHelpData = {
    page?: number;
    paginate?: number;
};

export type GetAdminHowHelpResponse = unknown;

export type PostAdminHowHelpData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminHowHelpResponse = unknown;

export type PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdResponse = unknown;

export type DeleteAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdResponse = unknown;

export type PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdStopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdStopResponse = unknown;

export type PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdRestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdRestoreResponse = unknown;

export type GetAdminAboutSectionsData = {
    page?: number;
    paginate?: number;
};

export type GetAdminAboutSectionsResponse = unknown;

export type PostAdminAboutSectionsData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminAboutSectionsResponse = unknown;

export type PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdResponse = unknown;

export type DeleteAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdResponse = unknown;

export type PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdStopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdStopResponse = unknown;

export type PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdRestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdRestoreResponse = unknown;

export type GetAdminDownloadSectionResponse = unknown;

export type PostAdminDownloadSectionData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
        google_play_link?: string;
        apple_store_link?: string;
    };
};

export type PostAdminDownloadSectionResponse = unknown;

export type GetAdminAboutData = {
    page?: number;
    paginate?: number;
};

export type GetAdminAboutResponse = unknown;

export type PostAdminAboutStoreAboutData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminAboutStoreAboutResponse = unknown;

export type PostAdminAboutStoreHowOrderData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        description_ar?: string;
        description_en?: string;
        link?: string;
    };
};

export type PostAdminAboutStoreHowOrderResponse = unknown;

export type DeleteAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5Response = unknown;

export type PostAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5StopResponse = unknown;

export type PostAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5RestoreResponse = unknown;

export type GetAdminSiteOffersData = {
    page?: number;
    paginate?: number;
};

export type GetAdminSiteOffersResponse = unknown;

export type PostAdminSiteOffersData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
        price_before_discount?: number;
        price_after_discount?: number;
    };
};

export type PostAdminSiteOffersResponse = unknown;

export type PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210Data = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
        price_before_discount?: number;
        price_after_discount?: number;
    };
};

export type PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210Response = unknown;

export type DeleteAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210Response = unknown;

export type PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210StopResponse = unknown;

export type PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210RestoreResponse = unknown;

export type GetAdminGuaranteeRightData = {
    page?: number;
    paginate?: number;
};

export type GetAdminGuaranteeRightResponse = unknown;

export type PostAdminGuaranteeRightData = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminGuaranteeRightResponse = unknown;

export type PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33Data = {
    accept?: string;
    formData?: {
        title_ar?: string;
        title_en?: string;
        image?: (Blob | File);
        description_ar?: string;
        description_en?: string;
    };
};

export type PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33Response = unknown;

export type DeleteAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33Response = unknown;

export type PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33StopResponse = unknown;

export type PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33RestoreResponse = unknown;

export type GetAdminPartnersData = {
    page?: number;
    paginate?: number;
};

export type GetAdminPartnersResponse = unknown;

export type PostAdminPartnersData = {
    accept?: string;
    formData?: {
        image?: (Blob | File);
    };
};

export type PostAdminPartnersResponse = unknown;

export type PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7Data = {
    accept?: string;
    formData?: {
        image?: (Blob | File);
    };
};

export type PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7Response = unknown;

export type DeleteAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7Response = unknown;

export type PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7StopData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7StopResponse = unknown;

export type PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7RestoreData = {
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7RestoreResponse = unknown;

export type GetAdminTicketsData = {
    page?: number;
    paginate?: number;
};

export type GetAdminTicketsResponse = unknown;

export type GetAdminTicketsFd3A3D51755B4FecBa9aA162B21188CeMessagesData = {
    page?: number;
    paginate?: number;
};

export type GetAdminTicketsFd3A3D51755B4FecBa9aA162B21188CeMessagesResponse = unknown;

export type PostAdminTicketsSendMessageData = {
    formData?: {
        ticket_id?: string;
        content?: string;
        type?: string;
    };
};

export type PostAdminTicketsSendMessageResponse = unknown;

export type GetClientOrdersData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * receiving_offer - accepted - completed
     */
    statusArray?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetClientOrdersResponse = unknown;

export type GetClientOrdersC5Ad5169F88D4Acc8D4F6C985706B224Data = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetClientOrdersC5Ad5169F88D4Acc8D4F6C985706B224Response = unknown;

export type PostClientOrdersC5Ad5169F88D4Acc8D4F6C985706B224ConfirmDeliveryData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        code?: number;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostClientOrdersC5Ad5169F88D4Acc8D4F6C985706B224ConfirmDeliveryResponse = unknown;

export type PostClientOrderRateData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        order_id?: string;
        rate?: number;
        comment?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostClientOrderRateResponse = unknown;

export type PostClientOffer96Be9E84956A429889Bd9Bd3C58E251eAcceptData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostClientOffer96Be9E84956A429889Bd9Bd3C58E251eAcceptResponse = unknown;

export type GetClientServicesData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetClientServicesResponse = unknown;

export type GetProviderSubscriptionPlansData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    paginate?: number;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderSubscriptionPlansResponse = unknown;

export type PostProviderSubscriptionSubscribeData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        plan_id?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostProviderSubscriptionSubscribeResponse = unknown;

export type GetProviderSubscriptionCheckData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderSubscriptionCheckResponse = unknown;

export type GetProviderProfileData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderProfileResponse = unknown;

export type PostProviderProfileData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        name?: string;
        owner_name?: string;
        mobile?: number;
        phone?: number;
        latitude?: number;
        longitude?: number;
        address?: string;
        branches?: string;
        /**
         * spare_parts or towing or maintenance
         */
        services?: string;
        'spare_part_brands[]'?: string;
        is_delivery_available?: number;
        is_video_call_available?: number;
        is_voice_call_available?: number;
        terms_and_conditions_accepted?: number;
        /**
         * new,used,both
         */
        part_condition?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostProviderProfileResponse = unknown;

export type PutProviderProfileData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        name?: string;
        owner_name?: string;
        mobile?: number;
        phone?: number;
        latitude?: number;
        longitude?: number;
        address?: string;
        branches?: string;
        services?: string;
        'spare_part_brands[]'?: string;
        is_delivery_available?: number;
        is_video_call_available?: number;
        is_voice_call_available?: number;
        terms_and_conditions_accepted?: number;
        part_condition?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PutProviderProfileResponse = unknown;

export type GetProviderMeData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderMeResponse = unknown;

export type GetProviderF84Fd31930E54Ea49C2881B822045EbcData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderF84Fd31930E54Ea49C2881B822045EbcResponse = unknown;

export type GetProviderSearchData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    lat?: number;
    lng?: number;
    paginate?: number;
    sort?: string;
    /**
     * spare_parts,towing,maintenance
     */
    type?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderSearchResponse = unknown;

export type GetProviderOrdersData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * can_submit - already_submit - accepted - finished
     */
    status?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderOrdersResponse = unknown;

export type GetProviderOrders1D9De514C4E149878Eb90909556C7186Data = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    /**
     * API
     */
    xRequestedWith?: string;
};

export type GetProviderOrders1D9De514C4E149878Eb90909556C7186Response = unknown;

export type PostProviderOrderRateData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        order_id?: string;
        rate?: number;
        comment?: string;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostProviderOrderRateResponse = unknown;

export type PostProviderOrdersC5Ad5169F88D4Acc8D4F6C985706B224ConfirmDeliveryData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        [key: string]: unknown;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostProviderOrdersC5Ad5169F88D4Acc8D4F6C985706B224ConfirmDeliveryResponse = unknown;

export type PostProviderOfferData = {
    /**
     * accepts: ar, en
     */
    contentLanguage?: string;
    formData?: {
        order_id?: string;
        price?: number;
        delivery_fee?: number;
    };
    /**
     * API
     */
    xRequestedWith?: string;
};

export type PostProviderOfferResponse = unknown;

export type GetPagesHowWeHelpResponse = unknown;

export type GetPagesRightsPaginatedData = {
    page?: number;
    paginate?: number;
};

export type GetPagesRightsPaginatedResponse = unknown;

export type GetPlatformReviewsData = {
    page?: number;
    paginate?: number;
};

export type GetPlatformReviewsResponse = unknown;

export type GetMessagesData = {
    accept?: string;
};

export type GetMessagesResponse = unknown;

export type PostMessagesSendData = {
    accept?: string;
    requestBody?: {
        [key: string]: unknown;
    };
};

export type PostMessagesSendResponse = unknown;

export type GetLandingSlidersResponse = unknown;

export type GetLandingServicesResponse = unknown;

export type GetLandingSiteOffersResponse = unknown;

export type GetLandingPlansResponse = unknown;

export type GetLandingHowHelpResponse = unknown;

export type GetLandingAboutSectionsResponse = unknown;

export type GetLandingDownloadSectionResponse = unknown;

export type GetLandingGuaranteeRightsResponse = unknown;

export type GetLandingPlatformReviewsResponse = unknown;

export type GetLandingPartnersResponse = unknown;

export type GetLandingMostRatedProvidersResponse = unknown;

export type GetLandingOrdersNumbersResponse = unknown;

export type GetLandingContactResponse = unknown;

export type GetLandingAboutResponse = unknown;

export type GetLandingHowOrderResponse = unknown;

export type $OpenApiTs = {
    '/shared/auth/me': {
        get: {
            req: GetSharedAuthMeData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/shared/auth/register': {
        post: {
            req: PostSharedAuthRegisterData;
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/shared/auth/send-otp': {
        post: {
            req: PostSharedAuthSendOtpData;
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/shared/auth/verify-otp': {
        post: {
            req: PostSharedAuthVerifyOtpData;
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/shared/auth/logout': {
        post: {
            req: PostSharedAuthLogoutData;
            res: {
                /**
                 * OK
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/shared/auth/edit-profile': {
        post: {
            req: PostSharedAuthEditProfileData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/shared/auth/change-phone': {
        post: {
            req: PostSharedAuthChangePhoneData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/shared/auth/verify-change-phone': {
        post: {
            req: PostSharedAuthVerifyChangePhoneData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/shared/auth/update-settings': {
        put: {
            req: PutSharedAuthUpdateSettingsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/brands': {
        get: {
            req: GetBrandsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/site_offers': {
        get: {
            req: GetSiteOffersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/cities': {
        get: {
            req: GetCitiesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/brands/Alfa_Romeo/models': {
        get: {
            req: GetBrandsAlfaRomeoModelsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/order_spare_part': {
        post: {
            req: PostClientOrderSparePartData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/vin/JN8AT3MM3PW009894': {
        get: {
            req: GetVinJn8At3Mm3Pw009894Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/chat': {
        post: {
            req: PostChatData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/chat/message': {
        post: {
            req: PostChatMessageData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/tickets': {
        get: {
            req: GetTicketsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/ticket/b33c269e-b489-415e-842f-65472771a0f3': {
        get: {
            req: GetTicketB33C269eB489415E842F65472771A0F3Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/ticket': {
        post: {
            req: PostTicketData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/ticket/message': {
        post: {
            req: PostTicketMessageData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/call/make': {
        post: {
            req: PostCallMakeData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/call/accept': {
        post: {
            req: PostCallAcceptData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/call/refuse': {
        post: {
            req: PostCallRefuseData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/call/end': {
        post: {
            req: PostCallEndData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/notification/index': {
        get: {
            req: GetNotificationIndexData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/notification/unread_count': {
        get: {
            req: GetNotificationUnreadCountData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/notification/mark_as_read': {
        post: {
            req: PostNotificationMarkAsReadData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/orders': {
        get: {
            req: GetAdminOrdersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/orders/1d9de514-c4e1-4987-8eb9-0909556c7186': {
        get: {
            req: GetAdminOrders1D9De514C4E149878Eb90909556C7186Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/orders/1d9de514-c4e1-4987-8eb9-0909556c7186/offers': {
        get: {
            req: GetAdminOrders1D9De514C4E149878Eb90909556C7186OffersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/orders/89572a05-e77b-48dc-8e1b-645fe0c82b6a/chat': {
        get: {
            req: GetAdminOrders89572A05E77B48Dc8E1B645Fe0C82B6aChatData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/setting/calls': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/setting': {
        get: {
            req: GetSettingData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/setting': {
        post: {
            req: PostAdminSettingData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/cities': {
        get: {
            req: GetAdminCitiesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminCitiesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/cities/81a53c06-4069-4120-b9ae-6a4314cd4ada': {
        put: {
            req: PutAdminCities81A53C0640694120B9Ae6A4314Cd4AdaData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/cities/b4a07276-1baf-43b0-8068-c03fdabf2626': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/cities/0e368569-8d07-4efb-a367-182dd5e2db42/stop': {
        post: {
            req: PostAdminCities0E3685698D074EfbA367182Dd5E2Db42StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/cities/0e368569-8d07-4efb-a367-182dd5e2db42/restore': {
        post: {
            req: PostAdminCities0E3685698D074EfbA367182Dd5E2Db42RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-profiles': {
        get: {
            req: GetAdminProviderProfilesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-profiles/verify/09d88c1d-fd8a-424d-9e7c-a5d2391cdbd3': {
        post: {
            req: PostAdminProviderProfilesVerify09D88C1dFd8A424D9E7cA5D2391Cdbd3Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-profiles/decline/02b915a7-5a56-4711-8b4a-eb110408a090': {
        post: {
            req: PostAdminProviderProfilesDecline02B915A75A5647118B4aEb110408A090Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-profiles/stop/02b915a7-5a56-4711-8b4a-eb110408a090': {
        post: {
            req: PostAdminProviderProfilesStop02B915A75A5647118B4aEb110408A090Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-profiles/restore/02b915a7-5a56-4711-8b4a-eb110408a090': {
        post: {
            req: PostAdminProviderProfilesRestore02B915A75A5647118B4aEb110408A090Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/users': {
        get: {
            req: GetAdminUsersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminUsersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/users/72d5778f-b67b-4e97-b4e2-f98f695162a7': {
        get: {
            req: GetAdminUsers72D5778fB67B4E97B4E2F98F695162A7Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/users/b2ef1c4f-918a-4f34-9d2f-97ce28c2772f': {
        put: {
            req: PutAdminUsersB2Ef1C4F918A4F349D2F97Ce28C2772FData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/users/b4a07276-1baf-43b0-8068-c03fdabf2626': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/users/0e368569-8d07-4efb-a367-182dd5e2db42/stop': {
        post: {
            req: PostAdminUsers0E3685698D074EfbA367182Dd5E2Db42StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/users/0e368569-8d07-4efb-a367-182dd5e2db42/restore': {
        post: {
            req: PostAdminUsers0E3685698D074EfbA367182Dd5E2Db42RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/message-templates': {
        get: {
            req: GetAdminMessageTemplatesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/message-templates/2': {
        get: {
            req: GetAdminMessageTemplates2Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/message-templates/5': {
        post: {
            req: PostAdminMessageTemplates5Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/services': {
        get: {
            req: GetAdminServicesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminServicesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/services/b11d171d-eec1-4474-a3d2-6ef6881023ae': {
        post: {
            req: PostAdminServicesB11D171dEec14474A3D26Ef6881023AeData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/services/b4a07276-1baf-43b0-8068-c03fdabf2626': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/services/d48c07f9-b8b8-46d9-8b3c-3ba8fcdbe611/stop': {
        post: {
            req: PostAdminServicesD48C07F9B8B846D98B3C3Ba8Fcdbe611StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/services/d48c07f9-b8b8-46d9-8b3c-3ba8fcdbe611/restore': {
        post: {
            req: PostAdminServicesD48C07F9B8B846D98B3C3Ba8Fcdbe611RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/commissions': {
        get: {
            req: GetAdminCommissionsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminCommissionsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/commissions/51a7447f-3bfd-4e89-a7f3-1969c8fb9330': {
        put: {
            req: PutAdminCommissions51A7447F3Bfd4E89A7F31969C8Fb9330Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/commissions/d48c07f9-b8b8-46d9-8b3c-3ba8fcdbe611/stop': {
        post: {
            req: PostAdminCommissionsD48C07F9B8B846D98B3C3Ba8Fcdbe611StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/commissions/d48c07f9-b8b8-46d9-8b3c-3ba8fcdbe611/restore': {
        post: {
            req: PostAdminCommissionsD48C07F9B8B846D98B3C3Ba8Fcdbe611RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/platform-reviews': {
        get: {
            req: GetAdminPlatformReviewsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminPlatformReviewsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/platform-reviews/5': {
        post: {
            req: PostAdminPlatformReviews5Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/platform-reviews/51a7447f-3bfd-4e89-a7f3-1969c8fb9330': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/platform-reviews/51a7447f-3bfd-4e89-a7f3-1969c8fb9330/stop': {
        post: {
            req: PostAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/platform-reviews/51a7447f-3bfd-4e89-a7f3-1969c8fb9330/restore': {
        post: {
            req: PostAdminPlatformReviews51A7447F3Bfd4E89A7F31969C8Fb9330RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/pages/rights': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/pages/rights/paginated': {
        get: {
            req: GetAdminPagesRightsPaginatedData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/pages': {
        post: {
            req: PostAdminPagesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/pages/5': {
        post: {
            req: PostAdminPages5Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/pages/51a7447f-3bfd-4e89-a7f3-1969c8fb9330': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-subscription-plans': {
        get: {
            req: GetAdminProviderSubscriptionPlansData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminProviderSubscriptionPlansData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-subscription-plans/945b42fc-a279-4ac5-8c00-77e635c87704': {
        post: {
            req: PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-subscription-plans/945b42fc-a279-4ac5-8c00-77e635c87704/stop': {
        post: {
            req: PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/provider-subscription-plans/945b42fc-a279-4ac5-8c00-77e635c87704/restore': {
        post: {
            req: PostAdminProviderSubscriptionPlans945B42FcA2794Ac58C0077E635C87704RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/city-services': {
        get: {
            req: GetAdminCityServicesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/city-services/13': {
        put: {
            req: PutAdminCityServices13Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/city-services/attach': {
        post: {
            req: PostAdminCityServicesAttachData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/city-services/detach': {
        post: {
            req: PostAdminCityServicesDetachData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/city-services/0e368569-8d07-4efb-a367-182dd5e2db42/stop': {
        post: {
            req: PostAdminCityServices0E3685698D074EfbA367182Dd5E2Db42StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/city-services/0e368569-8d07-4efb-a367-182dd5e2db42/restore': {
        post: {
            req: PostAdminCityServices0E3685698D074EfbA367182Dd5E2Db42RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/auth/login': {
        post: {
            req: PostAdminAuthLoginData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/auth/logout': {
        post: {
            req: PostAdminAuthLogoutData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/custom-notification': {
        post: {
            req: PostAdminCustomNotificationData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permission-groups': {
        get: {
            req: GetAdminPermissionGroupsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminPermissionGroupsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permission-groups/8e0ea4e1-b136-45ad-aa91-f4d0b47dcfaf': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permission-groups/d814419d-7555-4710-8e26-efeb66fc8fc2': {
        post: {
            req: PostAdminPermissionGroupsD814419D755547108E26Efeb66Fc8Fc2Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permission-groups/0e368569-8d07-4efb-a367-182dd5e2db42/stop': {
        post: {
            req: PostAdminPermissionGroups0E3685698D074EfbA367182Dd5E2Db42StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permission-groups/0e368569-8d07-4efb-a367-182dd5e2db42/restore': {
        post: {
            req: PostAdminPermissionGroups0E3685698D074EfbA367182Dd5E2Db42RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permission-groups/51a7447f-3bfd-4e89-a7f3-1969c8fb9330': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/permissions': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/messages': {
        get: {
            req: GetAdminMessagesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/messages/8899eddd-2567-40b6-bcaa-85ed7d53d226': {
        get: {
            req: GetAdminMessages8899Eddd256740B6Bcaa85Ed7D53D226Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/messages/reply/8899eddd-2567-40b6-bcaa-85ed7d53d226': {
        post: {
            req: PostAdminMessagesReply8899Eddd256740B6Bcaa85Ed7D53D226Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/messages/delete/6aa8ddfc-861c-4c42-b7c4-06dbb20627ad': {
        post: {
            req: PostAdminMessagesDelete6Aa8Ddfc861C4C42B7C406Dbb20627AdData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/sliders': {
        get: {
            req: GetAdminSlidersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminSlidersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/sliders/726a81ec-d9b5-43ad-946b-b77470b071f4': {
        post: {
            req: PostAdminSliders726A81EcD9B543Ad946bB77470B071F4Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/sliders/6193d4cd-ce8e-4b79-ba46-7e3c086206f3': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/sliders/726a81ec-d9b5-43ad-946b-b77470b071f4/stop': {
        post: {
            req: PostAdminSliders726A81EcD9B543Ad946bB77470B071F4StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/sliders/726a81ec-d9b5-43ad-946b-b77470b071f4/restore': {
        post: {
            req: PostAdminSliders726A81EcD9B543Ad946bB77470B071F4RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/how_help': {
        get: {
            req: GetAdminHowHelpData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminHowHelpData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/how_help/c0e70442-f191-4f3c-bb31-7ca396d574cd': {
        post: {
            req: PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/how_help/c0e70442-f191-4f3c-bb31-7ca396d574cd/stop': {
        post: {
            req: PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdStopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/how_help/c0e70442-f191-4f3c-bb31-7ca396d574cd/restore': {
        post: {
            req: PostAdminHowHelpC0E70442F1914F3cBb317Ca396D574CdRestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about_sections': {
        get: {
            req: GetAdminAboutSectionsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminAboutSectionsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about_sections/c0e70442-f191-4f3c-bb31-7ca396d574cd': {
        post: {
            req: PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about_sections/c0e70442-f191-4f3c-bb31-7ca396d574cd/stop': {
        post: {
            req: PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdStopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about_sections/c0e70442-f191-4f3c-bb31-7ca396d574cd/restore': {
        post: {
            req: PostAdminAboutSectionsC0E70442F1914F3cBb317Ca396D574CdRestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/download_section': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminDownloadSectionData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about': {
        get: {
            req: GetAdminAboutData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about/store_about': {
        post: {
            req: PostAdminAboutStoreAboutData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about/store_how_order': {
        post: {
            req: PostAdminAboutStoreHowOrderData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about/7ad421cd-9075-4a74-b2e1-e4298a1dc2b5': {
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about/7ad421cd-9075-4a74-b2e1-e4298a1dc2b5/stop': {
        post: {
            req: PostAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/about/7ad421cd-9075-4a74-b2e1-e4298a1dc2b5/restore': {
        post: {
            req: PostAdminAbout7Ad421Cd90754A74B2E1E4298A1Dc2B5RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/site_offers': {
        get: {
            req: GetAdminSiteOffersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminSiteOffersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/site_offers/e3ed5781-465b-4c16-879f-981812fb6210': {
        post: {
            req: PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/site_offers/e3ed5781-465b-4c16-879f-981812fb6210/stop': {
        post: {
            req: PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/site_offers/e3ed5781-465b-4c16-879f-981812fb6210/restore': {
        post: {
            req: PostAdminSiteOffersE3Ed5781465B4C16879F981812Fb6210RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/guarantee_right': {
        get: {
            req: GetAdminGuaranteeRightData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminGuaranteeRightData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/guarantee_right/716ae479-a414-4e1a-80a9-de253b560d33': {
        post: {
            req: PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/guarantee_right/716ae479-a414-4e1a-80a9-de253b560d33/stop': {
        post: {
            req: PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/guarantee_right/716ae479-a414-4e1a-80a9-de253b560d33/restore': {
        post: {
            req: PostAdminGuaranteeRight716Ae479A4144E1A80A9De253B560D33RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/partners': {
        get: {
            req: GetAdminPartnersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostAdminPartnersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/partners/862cfc1a-4563-4ac3-8bb8-5f75eeddd6e7': {
        post: {
            req: PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/partners/862cfc1a-4563-4ac3-8bb8-5f75eeddd6e7/stop': {
        post: {
            req: PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7StopData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/partners/862cfc1a-4563-4ac3-8bb8-5f75eeddd6e7/restore': {
        post: {
            req: PostAdminPartners862Cfc1A45634Ac38Bb85F75Eeddd6E7RestoreData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/tickets': {
        get: {
            req: GetAdminTicketsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/tickets/fd3a3d51-755b-4fec-ba9a-a162b21188ce/messages': {
        get: {
            req: GetAdminTicketsFd3A3D51755B4FecBa9aA162B21188CeMessagesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/admin/tickets/send_message': {
        post: {
            req: PostAdminTicketsSendMessageData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/orders': {
        get: {
            req: GetClientOrdersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/orders/c5ad5169-f88d-4acc-8d4f-6c985706b224': {
        get: {
            req: GetClientOrdersC5Ad5169F88D4Acc8D4F6C985706B224Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/orders/c5ad5169-f88d-4acc-8d4f-6c985706b224/confirm-delivery': {
        post: {
            req: PostClientOrdersC5Ad5169F88D4Acc8D4F6C985706B224ConfirmDeliveryData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/order/rate': {
        post: {
            req: PostClientOrderRateData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/offer/96be9e84-956a-4298-89bd-9bd3c58e251e/accept': {
        post: {
            req: PostClientOffer96Be9E84956A429889Bd9Bd3C58E251eAcceptData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/client/services': {
        get: {
            req: GetClientServicesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/subscription/plans': {
        get: {
            req: GetProviderSubscriptionPlansData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/subscription/subscribe': {
        post: {
            req: PostProviderSubscriptionSubscribeData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/subscription/check': {
        get: {
            req: GetProviderSubscriptionCheckData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/profile': {
        get: {
            req: GetProviderProfileData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostProviderProfileData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
        put: {
            req: PutProviderProfileData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/me': {
        get: {
            req: GetProviderMeData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/f84fd319-30e5-4ea4-9c28-81b822045ebc': {
        get: {
            req: GetProviderF84Fd31930E54Ea49C2881B822045EbcData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/search': {
        get: {
            req: GetProviderSearchData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/orders': {
        get: {
            req: GetProviderOrdersData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/orders/1d9de514-c4e1-4987-8eb9-0909556c7186': {
        get: {
            req: GetProviderOrders1D9De514C4E149878Eb90909556C7186Data;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/order/rate': {
        post: {
            req: PostProviderOrderRateData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/orders/c5ad5169-f88d-4acc-8d4f-6c985706b224/confirm-delivery': {
        post: {
            req: PostProviderOrdersC5Ad5169F88D4Acc8D4F6C985706B224ConfirmDeliveryData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/provider/offer': {
        post: {
            req: PostProviderOfferData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/pages/how_we_help': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/pages/rights/paginated': {
        get: {
            req: GetPagesRightsPaginatedData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/platform-reviews': {
        get: {
            req: GetPlatformReviewsData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/messages/': {
        get: {
            req: GetMessagesData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/messages/send': {
        post: {
            req: PostMessagesSendData;
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/sliders': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/services': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/site_offers': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/plans': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/how_help': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/about_sections': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/download_section': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/guarantee_rights': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/platform_reviews': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/partners': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/most_rated_providers': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/orders_numbers': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/contact': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/about': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/landing/how_order': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
};